spring:
  config:
    import: optional:file:./.env[.properties]
  application:
    name: first-API
  output:
    ansi:
      enabled: always
  jackson:
    date-format: 'dd.MM.yyyy'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

exception:
  trace: true

app:
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000